config/routes.rb
Rails.application.routes.draw do
  resources :fattachments
  resources :file_atts
  get 'attachments/index'

  get 'attachments/new'

  get 'attachments/create'

  get 'attachments/destroy'

  # Login
  root 'login#show'

  get 'sessions/create'
  get 'sessions/destroy'
  get 'login/show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :login, only: [:show]

  # Users
  resources :users

  # Issues
  resources :issues

  post '/issues/:id/watch', to: 'watches#create', as: 'watch'
  post '/issues/:id/vote', to: 'votes#create', as: 'vote'
  
  # Attachments
  resources :attachments, only: [:index, :new, :create, :destroy]
  post '/issues/:id/comments', to: 'comments#create', as: 'issue_comments'

end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  has_many :fattachments, :dependent => :destroy
  has_many :watches, dependent: :destroy
  has_many :users_watching, through: :watches, source: :user
  has_many :votes, dependent: :destroy
  has_many :users_voting, through: :votes, source: :user
  has_many :comments, dependent: :destroy
  has_many :users_commenting, through: :comments, source: :user
  enum kind: [:bug, :enhancement, :proposal, :task]
  enum priority: [:trivial, :minor, :major, :critical, :blocking]
  enum status: [:new_issue, :open, :on_hold, :resolved, :duplicate, :invalid_issue, :wont_fix, :closed]

  validates :title, presence: true
  validates :kind, presence: true
  validates :priority, presence: true
  validates :status, presence: true

  scope :opened, -> { where(status: ['new_issue', 'open']) }

  attr_accessor :current_user

  def watchers
    users_watching.size
  end

  def num_votes
    users_voting.size
  end

  def watched_by_current_user?
    users_watching.include? @current_user
  end

  def voted_by_current_user?
    users_voting.include? @current_user
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  include Commentable
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues?filter=[open|responsible|watching]
  # GET /issues.json
  def index
    params[:filter] = session[:filter] unless params[:filter]
    @issues = case params[:filter]
                when 'open'
                  Issue.opened
                when 'responsible'
                  Issue.where(user_id: @current_user.id)
                when 'watching'
                  issues_array = []
                  Issue.all.each do |issue|
                    issue.current_user = current_user
                    issues_array << issue if issue.watched_by_current_user?
                  end
                  issues_array
                else
                  Issue.all
              end
    session[:filter] = params[:filter]
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end
  

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    respond_to do |format|
      if @issue.save
        
        if params[:uploads]
          params[:uploads].each { |upload|
            @issue.fattachments.create(file: upload)
          }
        end
        
        add_comment(@issue, 'created this issue', current_user.id)
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      old = @issue.dup
      @issue.assign_attributes(issue_params)
      update_comment = set_update_comment
      if @issue.save
        
        if params[:uploads]
          params[:uploads].each { |upload|
            @issue.fattachments.create(file: upload)
          }
        end
        
        add_comment(@issue, update_comment, current_user.id) unless update_comment.empty?
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
        @issue = old
      end
    end
  end

  def set_update_comment
    update_comment = ''
    @issue.changed.each do |attr|
      key = attr.to_s
      value = @issue[attr].to_s
      value = 'any' if value.empty?
      if attr.to_s == 'status'
        value = humanize_status(value)
      elsif key == 'user_id'
        key = 'assignee'
        value = User.find_by_id(@issue[attr]).name if value != 'any'
      end
      update_comment += '* updated ' + key + ' to ' + value + "\n"
    end
    update_comment
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  helper_method :humanize_status

  def humanize_status(status)
    status.gsub('_issue', '').humanize
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :user_id, :kind, :priority, :status, :fileattachments)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def confirm_issue_form_text(issue)
    if find_issue(issue); 'Update issue'
    else 'Create issue'
    end
  end

  def cancel_issue_form_path(issue)
    if find_issue(issue); issue
    else issues_path
    end
  end

  def active_filter(filter)
    if session[:filter]
      'active' if session[:filter] == filter
    else
      'active' if filter == 'all'
    end
  end

  private

  def find_issue(issue)
    Issue.find_by_id(issue.id)
  end
end

app/views/issues/_form.html.erb
<%= form_for(@issue, :html => { :multipart => true }) do |f| %>
  <% if notice %>
      <div class="alert alert-success" role="alert"><p id="notice"><%= notice %></p></div>
  <% end %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <p id="error">
          <%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:
        </p>
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
      <ul>
      </ul>
    </div>
  <% end %>

  <script>
    function assignToMe() {
      var id = "<%= current_user.id %>";
      var select = document.getElementById('sel-user');
      select.value = id;
    }
  </script>

  <script>
    updateList = function() {
      var input = document.getElementById('file-selector');
      var output = document.getElementById('fileList');

      output.innerHTML   = '<ul class=\'attachment-list\'>';
      for (var i = 0; i < input.files.length; ++i) {
        if (i === input.files.length - 1) output.innerHTML += '<li class=\'attachment-li li-last\'>' + input.files.item(i).name + '</li>';
        else output.innerHTML += '<li class=\'attachment-li\'>' + input.files.item(i).name + '</li>';
      }
      output.innerHTML += '</ul>';
    }
  </script>

  <div class="container form-class container-new">
    <div class="row">
      <div class="col-md-8">
        <div id='title-and-description' class="field-group">
          <%= f.label :title, :class => 'text-muted label-group'%>
          <%= f.text_field :title, :required => true, :class => 'form-control text input-title' %>
        </div>

        <div class="field-group">
          <div class="field">
            <%= f.label :description, :class => 'text-muted label-group' %>
            <%= md_simple_editor('btn-sm') do %>
              <%= f.text_area :description, { :class => 'form-control form-description', :style => 'height: 150px'} %>
            <% end %>
            <i>Editor options not working? Refresh page.</i>
          </div>
        </div>

        <div class="field-group">
          <div class="field">
            <%= f.label :user_id, 'Asignee', :class => 'text-muted label-group' %>
            <%= f.collection_select(:user_id, User.all, :id, :name, {include_blank: true, include_hidden: false},
              {:class => "form-control small-select", :id =>"sel-user"}) %>
            <%= link_to 'Assign to me', '#', {:class => 'btn btn-link assign-link', :onclick => "assignToMe()", :remote => true }  %>
          </div>
        </div>

        <div class="field-group">
          <div class="field">
            <%= f.label :kind, :class => 'text-muted label-group' %>
            <%= f.select :kind, Issue.kinds.keys, {}, {class: "form-control small-select", required: true} %>
          </div>
        </div>

        <div class="field-group">
          <div class="field">
            <%= f.label :priority, :class => 'text-muted label-group' %>
            <%= f.select :priority, Issue.priorities.keys, {}, {class: "form-control small-select", required: true} %>
          </div>
        </div>

        <div class="field-group" id="attachments">
          <label class='text-muted label-group'>Attachments</label>
          <% if @issue.fattachments.size > 0 %>
            <ul id="atts" class='attachment-list'>
              <% @issue.fattachments.each do |att| %>
                  <li class='attachment-li'>
                    <%= link_to(att.file_file_name, att.file.url, :download => att.file_file_name) %>
                    <%= link_to 'Remove', att, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger button-remove' %>
                  </li>
              <% end %>
            </ul>
            <div class='li-last'></div>
          <% end %>

          <%= fields_for :attachments do |_| %>
            <div class="field">
              <div id="fileList"></div>
              <span class="btn btn-large btn-default btn-file">
                  Select file
                  <%= file_field_tag "uploads[]", type: :file, multiple: true, id: 'file-selector', onchange: 'javascript:updateList()' %>
              </span>
            </div>
          <% end %>
        </div>

        <div class="field-group">
          <div class="actions">
            <button name="commit" type="submit" class="btn btn-primary">
              <b><%= confirm_issue_form_text(@issue) %></b>
            </button>
            <%= link_to 'Cancel', cancel_issue_form_path(@issue), class: 'btn btn-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/issues/_newcomment.html.erb
<%= form_for [@issue, @issue.comments.new] do |c| %>
    <div class="field">
      <%= md_simple_editor('btn-sm')  do %>
          <%= c.text_area :acomment, { :class => 'form-control form-description', :style => 'height: 50px'} %>
      <% end %>
    </div>
    <div class="form-group">
      <%= c.submit 'Comment', class: 'btn btn-primary', :style => 'margin-top: 10px; margin-right: 10px' %>
      <i>Editor options not working? Refresh page.</i>
    </div>
<% end %>

app/views/issues/edit.html.erb
<h2>Edit issue</h2>
<hr />
<%= render 'form', issue: @issue %>

app/views/issues/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert"><p id="notice"><%= notice %></p></div>
<% end %>
<div id="issuesList">
  <h2>Issues</h2>

  <div class="row" id="filters">
    <div class="col-xs-1"><i>Filters: </i></div>
    <div class="col-xs-1"><a class="btn btn-default btn-block <%= active_filter('all') %>"
                             href=<%= issues_path(filter: 'all') %>>All</a></div>
    <div class="col-xs-1"><a class="btn btn-default btn-block <%= active_filter('open') %>"
                             href=<%= issues_path(filter: 'open') %>>Open</a></div>
    <div class="col-xs-1"><a class="btn btn-default btn-block <%= active_filter('responsible') %>"
                             href=<%= issues_path(filter: 'responsible') %>>My issues</a></div>
    <div class="col-xs-1"><a class="btn btn-default btn-block <%= active_filter('watching') %>"
                             href=<%= issues_path(filter: 'watching') %>>Watching</a></div>
    <div class="col-xs-6"></div>
    <div class="col-xs-1"><%= link_to 'New Issue', new_issue_path, class: 'btn btn-success' %></div>
  </div>

  </p>

  <div id="titolsTaula" class="row">
    <div class="col-xs-2"><b>Title</b></div>
    <div class="col-xs-1"><b>Type</b></div>
    <div class="col-xs-1"><b>Priority</b></div>
    <div class="col-xs-1"><b>Status</b></div>
    <div class="col-xs-1"><b>Votes</b></div>
    <div class="col-xs-2"><b>Asignee</b></div>
    <div class="col-xs-2"><b>Created</b></div>
    <div class="col-xs-2"><b>Updated</b></div>
  </div>

  <% @issues.each do |issue| %>

  <div id="item" class="row">
    <div class="col-xs-2"><%= link_to issue.title, issue %></div>
    <div class="col-xs-1"><p><%= issue.kind.humanize %></p></div>
    <div class="col-xs-1"><%= issue.priority.humanize %></div>
    <div class="col-xs-1"><%= humanize_status(issue.status) %></div>
    <div class="col-xs-1"><%= issue.num_votes %></div>
    <div class="col-xs-2"><% if issue.user %><%= issue.user.name %><% end %></div>
    <div class="col-xs-2"><%= distance_of_time_in_words_to_now(issue.created_at) %></div>
    <div class="col-xs-2"><%= distance_of_time_in_words_to_now(issue.updated_at) %></div>
  </div>
  <% end %>
  <br>
</div>

app/views/issues/new.html.erb
<h2>Create issue</h2>
<hr />
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert"><p id="notice"><%= notice %></p></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><p id="error"><%= flash[:alert] %></p></div>
<% end %>
<div class="row">
  <div class="col-xs-8">
    <h3> Issue: #<%= @issue.id %> </h3>
    <h2> <%= @issue.title %> </h2>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Description</h3>
      </div>
      <div class="panel-body">
        <p>
          <% if @issue.description.empty? %>
              <i>No description provided.</i>
          <% end %>
          <%= markdown(@issue.description) %>
        </p>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Comments (<%= @issue.comments.size %>)</h3>
      </div>
      <div class="panel-body">
        <% @issue.comments.each do |comment| %>
            <% u = User.find_by_id(comment.user_id)%>
            <%= render partial: 'comments/comment', locals: {comment: comment, user: u } %>
        <% end %>
      </div>
    </div>
    <%= render 'newcomment', issue: @issue %>
  </div>
  <div class="col-xs-4">
    <div class="btn-group btn-group-justified" role="group" aria-label="..." style="margin-top: 17px">
      <div class="btn-group" role="group">
        <a class="btn btn-primary" href="#" role="button">Resolve</a>
      </div>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Workflow
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right dropdown-menu-wide">
          <% Issue.statuses.each_key do |status| %>
            <li><%= link_to humanize_status(status), issue_path(@issue, issue: {status: status}), method: :put %></li>
          <% end %>
        </ul>
      </div>
      <%= link_to 'Edit', edit_issue_path(@issue), id: 'edit_issue' , class: 'btn btn-default' %>
      <%= link_to 'Delete', @issue, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
    <div class="panel panel-default" style="margin-top: 10px">
      <div class="panel-body">
        <p>
          <strong>Assignee:</strong>
          <% if @issue.user %>
            <%= @issue.user.name %> (<%= @issue.user.email %>)
          <% end %>
        </p>

        <p>
          <strong>Type:</strong>
          <%= @issue.kind %>
        </p>

        <p>
          <strong>Priority:</strong>
          <%= @issue.priority %>
        </p>

        <p>
          <strong>Status:</strong>
          <%= humanize_status(@issue.status) %>
        </p>

        <p>
          <l><strong>Watchers</strong></l>
          <span class="badge"><%= @issue.watchers %></span>
          <% if @issue.users_watching.exists? current_user.id %>
              <%= link_to 'Stop watching', watch_path(@issue), :method => :post%>
          <% else %>
              <%= link_to 'Watch', watch_path(@issue), :method => :post%>
          <% end %>
        </p>
        <p>
          <l><strong>Votes</strong></l>
          <span class="badge"><%= @issue.num_votes %></span>
          <% if @issue.users_voting.exists? current_user.id %>
              <%= link_to 'Remove vote', vote_path(@issue), :method => :post%>
          <% else %>
              <%= link_to 'Vote for this issue', vote_path(@issue), :method => :post%>
          <% end %>
        </p>
        <p>
          <br>
          <l><strong>Attachments</strong></l>
          <br>
          <% if @issue.fattachments.size > 0 %>
            <ul id="atts" class='attachment-list'>
              <% @issue.fattachments.each do |att| %>
                  <li class='attachment-li'>
                    <%= link_to(att.file_file_name, att.file.url, :download => att.file_file_name) %>
                  </li>
              <% end %>
            </ul>
            <div class='li-last'></div>
          <% else %>
            <label><i>No attached files.</i></label>
          <% end %>
        </p>

      </div>
    </div>
  </div>

</div>
<div class="row">
  <%= link_to 'Back', issues_path, class: 'btn btn-link'%>
</div>