config/routes.rb
Rails.application.routes.draw do
  resources :fattachments
  resources :file_atts
  get 'attachments/index'

  get 'attachments/new'

  get 'attachments/create'

  get 'attachments/destroy'

  # Login
  root 'login#show'

  get 'sessions/create'
  get 'sessions/destroy'
  get 'login/show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resource :login, only: [:show]

  # Users
  resources :users

  # Issues
  resources :issues

  post '/issues/:id/watch', to: 'watches#create', as: 'watch'
  post '/issues/:id/vote', to: 'votes#create', as: 'vote'
  
  # Attachments
  resources :attachments, only: [:index, :new, :create, :destroy]
  post '/issues/:id/comments', to: 'comments#create', as: 'issue_comments'

end

app/models/fattachment.rb
class Fattachment < ApplicationRecord
  belongs_to :issue

  has_attached_file :file

  do_not_validate_attachment_file_type :file
end

app/controllers/fattachments_controller.rb
class FattachmentsController < ApplicationController
  before_action :set_fattachment, only: [:show, :edit, :update, :destroy]

  # GET /fattachments
  # GET /fattachments.json
  def index
    @fattachments = Fattachment.all
  end

  # GET /fattachments/1
  # GET /fattachments/1.json
  def show
  end

  # GET /fattachments/new
  def new
    @fattachment = Fattachment.new
  end

  # GET /fattachments/1/edit
  def edit
  end

  # POST /fattachments
  # POST /fattachments.json
  def create
    @fattachment = Fattachment.new(fattachment_params)

    respond_to do |format|
      if @fattachment.save
        format.html { redirect_to @fattachment, notice: 'Attachment was successfully added.' }
        format.json { render :show, status: :created, location: @fattachment }
      else
        format.html { render :new }
        format.json { render json: @fattachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fattachments/1
  # PATCH/PUT /fattachments/1.json
  def update
    respond_to do |format|
      if @fattachment.update(fattachment_params)
        format.html { redirect_to @fattachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fattachment }
      else
        format.html { render :edit }
        format.json { render json: @fattachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fattachments/1
  # DELETE /fattachments/1.json
  def destroy
    @fattachment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Attachment was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fattachment
      @fattachment = Fattachment.find(params[:id])
    end
    
    #

    # Never trust parameters from the scary internet, only allow the white list through.
    def fattachment_params
      params.fetch(:fattachment, {})
    end
end

app/helpers/fattachments_helper.rb
module FattachmentsHelper
end

app/views/fattachments/_form.html.erb
<%= form_for(fattachment) do |f| %>
  <% if fattachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fattachment.errors.count, "error") %> prohibited this fattachment from being saved:</h2>

      <ul>
      <% fattachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fattachments/edit.html.erb
<h1>Editing Fattachment</h1>

<%= render 'form', fattachment: @fattachment %>

<%= link_to 'Show', @fattachment %> |
<%= link_to 'Back', fattachments_path %>

app/views/fattachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fattachments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fattachments.each do |fattachment| %>
      <tr>
        <td><%= link_to 'Show', fattachment %></td>
        <td><%= link_to 'Edit', edit_fattachment_path(fattachment) %></td>
        <td><%= link_to 'Destroy', fattachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fattachment', new_fattachment_path %>

app/views/fattachments/new.html.erb
<h1>New Fattachment</h1>

<%= render 'form', fattachment: @fattachment %>

<%= link_to 'Back', fattachments_path %>

app/views/fattachments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fattachment_path(@fattachment) %> |
<%= link_to 'Back', fattachments_path %>